# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-api-gateway-rest-api
  description: This component is responsible for deploying an API Gateway REST API
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component



